name: Readme Generate

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'
  workflow_dispatch:

jobs:
  readme-gen:
    runs-on: ubuntu-latest
    # if: github.repository_owner == 'Anduin2017'
    steps:
      - uses: actions/checkout@v2
      - run: node ./.github/readme-generate.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[ci skip] Automatic generate readme"
          file_pattern: ":/*.md"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
